### PR TITLE
Restructure

### PR DESCRIPTION
**Pull request by theMikeD**
* refactoring, documentation
* clean phpcs using Wordpress-Extra
* unit tests
* for the taxonomy change option, only public taxonomies are listed
* for the taxonomy change option, WPML-translated terms are also moved
* for the term merge option, if all terms to be merged have the same parent term, the merged term will also have that parent term.
* for the term parent option, if one of hte supplied terms is also the term selected to be the parent, no terms are adjusted.
* new filter term_management_tools_changed_taxonomy__terms_list_as_supplied
* new filter term_management_tools_changed_taxonomy__terms_list_including_child_terms

### CODE REVIEW

**Comment by theMikeD** [comment]
Screen Shot 2020-11-26 at 5 47 53 PM

**Comment by theMikeD** [comment]
Haven't done the tests for the WMPL part because frankly I can't figure out how to do them.

**Comment by scribu** [comment]
Hey Mike,

Thanks for stepping up!

Instead of merging this PR, I think it would make more sense for your fork to become the blessed successor.

I can give you write access to the wp.org SVN repo for plugin, so that you can push your fork to it.

What do you think?

**Comment by theMikeD** [comment]
Sure, that works! Shoot me an email and we'll get it sorted :)

**Comment by scribu** [comment]
Alright, you now have commit access to https://wordpress.org/plugins/term-management-tools/

Don't hesitate to reach out if you encounter any issues while making a new release.

**Comment by theMikeD** [comment]
Thanks! I'll be a good steward :)

**Comment by theMikeD** [comment]
FTR I've added some docs to my site for the plugin, so I'll be changing the URL for it as well.

https://www.codenamemiked.com/plugins/term-management-tools/

I expect a new release will be ready on Monday.

**Comment by theMikeD** [comment]
Version 2 is done now and will be pushed to the repo today.
https://github.com/theMikeD/wp-term-management-tools/releases/tag/2.0.0
Put a message here so I know you see this, then I'll delete this PR.

**Comment by scribu** [comment]
Excellent. I'll point people to your fork once the release is out on wp.org.

**Pull request closed without merging**
